### ISSUE TITLE
Update the CDK for the stage 1

### ISSUE THREAD

**Issue by hitohata** [genesis-tech-tribe/nishiki-backend#138]
## Feature Title

To release Nishiki Stage 1, we need to update the CDK.

## Acceptance Criteria

- [x] #139
- [x] #140
- [x] Add a main function #126 
- [x] #201
- [x] #239
- [x] #153

## Technical Details

- API Changes:
- Database Changes:
- Dependencies:

## Additional Context

None

**Comment by taniguchiiqqq** [comment]
I updated the Acceptance Criteria and added `Call user initialize function by Cognito Trigger` because I made a `Add a user-initialize-function function` #201 PR that only includes updating the Cognito trigger setting.
