### ISSUE TITLE
CDK create API Gateway and Cognito

### ISSUE THREAD

**Issue by hitohata** [genesis-tech-tribe/nishiki-backend#16]
## Abstract

To test OAth, create API Gateway and Cognito

## Description

Cognito is federeted identity

## What should do

* write CDK code

**Comment by hitohata** [comment]
@taniguchiiqqq 
The identity pool seems still an alpha release. In my humble opinion, it's OK to use it. If it gets GA, we just change this module.
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito-readme.html

**Comment by taniguchiiqqq** [comment]
@hitohata 
Thank you for the info! How do you think that we use only the Cognito user pool? The user pool's third-party sign-in seems to satisfy our demand, enabling users to sign in by Google accounts.
Please be careful with the difference between the two ways of federation by user pools or identity pools. I was confused.
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-identity-federation.html
> Sign-in through a third party (federation) is available in Amazon Cognito user pools. This feature is independent of federation through Amazon Cognito identity pools (federated identities).

**Comment by hitohata** [comment]
@taniguchiiqqq 
I'm sorry, I completely misunderstood. The id id-pools are supported.
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito-readme.html#identity-providers

Let's use it.

**Comment by taniguchiiqqq** [comment]
@hitohata 
May I confirm that you mean we are going to use only a user pool, not id pools? I mean, the link you mentioned is about user pools.
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito-readme.html#identity-providers

**Comment by hitohata** [comment]
@taniguchiiqqq 
Yes, I think we should use the user pool. Our requirement is entrusting on managed service to achieve the authentication.

**Comment by taniguchiiqqq** [comment]
@hitohata 
I totally agree with it!
