### ISSUE TITLE
Document test doesn't work

### ISSUE THREAD

**Issue by hitohata** [genesis-tech-tribe/nishiki-backend#160]
## Bug Description

I found that the typedoc test in the GithubActions doesn't work correctly.

## Steps to Reproduce

1. Run GithubActions with bad code
2. The test will fail but the GithubAction's test will pass.

## Expected Behavior

GuthubAction's test should fail

## Screenshots

![image](https://github.com/genesis-tech-tribe/nishiki-backend/assets/43802663/ab4f4460-3ec5-4e42-8065-e9d69489aefe)

## Additional Context

See the 'Build Documents' section. The error occurred but the test was marked as OK.

[Any other context about the problem.](https://github.com/genesis-tech-tribe/nishiki-backend/actions/runs/7207297096/job/19633875274)

**Comment by taniguchiiqqq** [comment]
OMG, I didn't notice. Thanks a lot!
