### ISSUE TITLE
Add GitHub Actions for Test

### ISSUE THREAD

**Issue by hitohata** [genesis-tech-tribe/nishiki-backend#23]
## Abstract

Add GitHub Actions for Test

## Description

- Run test command for both backend and cdk at once on pull request creation and push.

https://docs.github.com/en/actions/quickstart

**Comment by uskayyyyy** [comment]
@hitohata @taniguchiiqqq 
I heard that this issue is not in a rush. What date would you like it to be due?

**Comment by uskayyyyy** [comment]
@hitohata 
Sure! I will try.
