### ISSUE TITLE
fix GetUserService

### ISSUE THREAD

**Issue by taniguchiiqqq** [genesis-tech-tribe/nishiki-backend#272]
## Bug Description

It got auth token instead of a raw header like `Bearer authtoken`

**Comment by taniguchiiqqq** [comment]
I should've used `email` property of the token instead of `sub`.
This is the result of decoding the token.
```
{
    "at_hash": "hash-string",
    "sub": "user-uid-string",
    "cognito:groups": [
        "us-west-2_xxxxxxxxx_Google"
    ],
    "email_verified": false,
    "iss": "https://cognito-idp.us-west-2.amazonaws.com/us-west-2_xxxxxxxxx",
    "cognito:username": "Google_111111111111111111111",
    "nonce": "string",
    "origin_jti": "jti-claim-string",
    "aud": "audience-string",
    "identities": [
        {
            "userId": "111111111111111111111",
            "providerName": "Google",
            "providerType": "Google",
            "issuer": null,
            "primary": "true",
            "dateCreated": "1706559238075"
        }
    ],
    "token_use": "id",
    "auth_time": 1706604995,
    "nickname": "Y T",
    "exp": 1706608595,
    "iat": 1706604995,
    "jti": "jti-string",
    "email": "test@test.com"
}
```

**Comment by hitohata** [comment]
I'm curious about the 'sub' is the unique ID of the user? In other words, we did not have to implement the create User ID method? Anyway, we won't change it, though.

**Comment by taniguchiiqqq** [comment]
@hitohata 
Exactly. Sorry, I might have overlooked the information. But the good thing is our code is designed to be able to switch authentication services.
https://docs.aws.amazon.com/ja_jp/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-id-token.html
