### ISSUE TITLE
Fix: Cognito auth signup doesn't work

### ISSUE THREAD

**Issue by taniguchiiqqq** [genesis-tech-tribe/nishiki-backend#286]
## Bug Description

Fix: Cognito auth signup doesn't work

## Steps to Reproduce

1. Go to 'Hosted signup UI'
2. Click on 'Google login'
3. see error in response `error_description: PreSignUp failed with error 2024-02-04T01:23:26.945Z fddd4e41-54b3-488c-b329-adeae0ecf465 Task timed out after 3.07 seconds. 
` but user data created in Dynamo not in Cognito user pool
4. do 1, and 2. again
5. see error in response `error_description: PreSignUp failed with error HTTP request failed with status 400: Bad Request. 
` nothing happened to cognito user pool
6. delete created data in Dynamo, and do 1. and 2. again
7. login suceeded

## Expected Behavior

after doing 1. and 2., login should be success.

## Additional Context

If I didn't do the 4. process, login couldn't be a success.

**Comment by hitohata** [comment]
If you changed the lambda's duration time, would this situation change? For example, the lambda duration time changes to 10 sec (now, it is 3 sec.).
I think this error comes from the duration of the hook function. The Cognito cannot receive any response because the hook function is timeout before returning something.

**Comment by hitohata** [comment]
If this situation doesn't change, we should consider using a messaging service like SQS.

**Comment by taniguchiiqqq** [comment]
@hitohata 
Thank you for your help. I've changed the duration time to 5 sec because of [the Cognito trigger's limitation](https://docs.aws.amazon.com/ja_jp/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html). Then the timeout error seemed solved. Now I have a weird situation that the cognito triggered function is invoked twice when a user try to signup. Now I'm figuring it out.
