### ISSUE TITLE
Members are not deleted even though the 204 response is returned

### ISSUE THREAD

**Issue by nickyito** [genesis-tech-tribe/nishiki-backend#321]
## Bug Description

Members are not deleted even though the 204 response is returned. This issue is observed on the frontend, but it should stem from the backend.

## Steps to reproduce the bug

1. Navigate to the `env.development.local` file in the frontend repository on your local machine.
2. In this file, specify the backend API endpoint as the one for the AWS development environment.
3. Launch the local server for the frontend by running the command `npm run dev` and visit the local app in your browser.
4. Attempt to delete a member of a group while using multiple accounts for testing purposes.
5. Even though you will receive a 204 response through the API call, the user you attempted to delete will still be present.

## Expected Behavior

The user should be deleted after receiving a 204 response.

## Screen Capture

In the video, although the page is refreshed after attempting to delete the user, it still persists.

https://github.com/nishiki-tech/nishiki-backend/assets/99148565/47557650-c14f-4ab6-92cc-a85d734d980b

**Comment by hitohata** [comment]
The root of course is the group repository.
After a group is modified in the use case, the object is saved using the update method of the repository.
https://github.com/nishiki-tech/nishiki-backend/blob/develop/backend/main/src/Group/UseCases/DeleteUserFromGroupUseCase/DeleteUserFromGroupUseCase.ts#L76
But, the operation of which is just saving the object.
https://github.com/nishiki-tech/nishiki-backend/blob/develop/backend/main/src/Group/Repositories/GroupRepository.ts#L81

To fix this bug, it is needed to change this method to 
save the updated object.

**Comment by taniguchiiqqq** [comment]
I appreciate your report. As @hitohata said, The cause is that the update Group method couldn't cover the case of deletion of users. It was able just to update the Group information and add users. I'll add `deleteUserFromGroup` method to Dynamo DB Client class and modify the update method to call `deleteUserFromGroup` so that the update method delete the relationship between users and a group.
