### ISSUE TITLE
About the return type of repository's find method and FindUserCase

### ISSUE THREAD

**Issue by taniguchiiqqq** [genesis-tech-tribe/nishiki-backend#74]
## Your Question

Is it better that the return type of both repository's find method and FindUserCase is Null?

## Why are you asking?

I found IUserRepository use null for find method. but FindUserUseCase use undefined. 

## Additional Information

I noticed it when I saw some warnings in the following files. Then, it should be null instead of undefined.

CreateUserNameUseCase.test.ts
```
vi.spyOn(mockUserRepository, "find").mockReturnValueOnce(
	Promise.resolve(undefined),
);
```

UpdateUserNameUseCase.test.ts
```typescript:
vi.spyOn(mockUserRepository, "find").mockReturnValueOnce(undefined);
```

**Comment by hitohata** [comment]
I believe using 'null' is more appropriate in this case, as it is more explicit than 'undefined'.

Related to "Additional Information", you are correct, it was my mistake.

**Comment by taniguchiiqqq** [comment]
@hitohata 
Thank you for your opinion! I agree that using null in IUserRepository's find method. 
How about in FindUserUseCase.ts? now it can return undefined when it cannot find a user. Honestly, I don't have a solid idea about it.
