### ISSUE TITLE
Create Queries for Group

### ISSUE THREAD

**Issue by taniguchiiqqq** [genesis-tech-tribe/nishiki-backend#88]
## Feature Title

A concise title for the new feature.

## Acceptance Criteria

- GetGroupInfo
- GetGroupList

## Technical Details

- API Changes:
- Database Changes:
- Dependencies:

## Additional Context

Any other internal context or references.

**Comment by hitohata** [comment]
Divide into the following issues.

* GetGroupInfo #230
* GetGroupList #236
