### ISSUE TITLE
Create Query for Container

### ISSUE THREAD

**Issue by taniguchiiqqq** [genesis-tech-tribe/nishiki-backend#91]
## Feature Title

Create Query for Container

## Acceptance Criteria

- [x] GetContainerInfo

## Technical Details

- API Changes:
- Database Changes:
- Dependencies:

## Additional Context

Any other internal context or references.

**Comment by hitohata** [comment]
This one is resolved [here](https://github.com/genesis-tech-tribe/nishiki-backend/issues/174).
